#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#
# Copyright 2026 Mohammad Haghpanah.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Custom BB60C Sweep GUI (NOT generated by GRC).
# GRC overwrites untitled.py on Generate/Execute — keep this file as the
# polished application entry point.
#

"""
@file bb60c_sweep_gui.py
@brief BB60C sweep GUI with side panel, debounce, and QSS styling.

Uses QT GUI Time Sink; the default horizontal \"Time\" axis title is cleared.
"""

from packaging.version import Version as StrictVersion

if __name__ == '__main__':
    import ctypes
    import sys
    if sys.platform.startswith('linux'):
        try:
            x11 = ctypes.cdll.LoadLibrary('libX11.so')
            x11.XInitThreads()
        except Exception:
            print("Warning: failed to XInitThreads()")

from PyQt5 import Qt
from PyQt5 import QtCore
from gnuradio import qtgui
from gnuradio.qtgui import Range, RangeWidget
import sip
from gnuradio import bb60c
from gnuradio import blocks
from gnuradio import gr
import sys
import signal
import os


def _fmt_hz(value):
    """Format Hz values for the status line."""
    abs_v = abs(value)
    if abs_v >= 1e9:
        return "{:.3f} GHz".format(value / 1e9)
    if abs_v >= 1e6:
        return "{:.3f} MHz".format(value / 1e6)
    if abs_v >= 1e3:
        return "{:.3f} kHz".format(value / 1e3)
    return "{:.1f} Hz".format(value)


class bb60c_sweep_gui(gr.top_block, Qt.QWidget):
    """
    @brief Top block window for BB60C continuous sweep with live controls.
    """

    def __init__(self):
        gr.top_block.__init__(self, "BB60C Sweep", catch_exceptions=True)
        Qt.QWidget.__init__(self)
        self.setWindowTitle("BB60C Sweep")
        self.resize(1280, 820)
        qtgui.util.check_set_qss()
        try:
            self.setWindowIcon(Qt.QIcon.fromTheme('gnuradio-grc'))
        except Exception:
            pass

        self._apply_stylesheet()

        root = Qt.QVBoxLayout(self)
        root.setContentsMargins(14, 14, 14, 14)
        root.setSpacing(10)

        header = Qt.QVBoxLayout()
        title = Qt.QLabel("BB60C Sweep")
        title.setObjectName("appTitle")
        subtitle = Qt.QLabel(
            "Live spectrum sweep · Signal Hound BB60C")
        subtitle.setObjectName("appSubtitle")
        header.addWidget(title)
        header.addWidget(subtitle)
        root.addLayout(header)

        splitter = Qt.QSplitter(QtCore.Qt.Horizontal)
        splitter.setChildrenCollapsible(False)
        root.addWidget(splitter, 1)

        side_frame = Qt.QFrame()
        side_frame.setObjectName("sidePanel")
        side_frame.setMinimumWidth(360)
        side_frame.setMaximumWidth(430)
        side_layout = Qt.QVBoxLayout(side_frame)
        side_layout.setContentsMargins(12, 12, 12, 12)
        side_layout.setSpacing(8)

        side_scroll = Qt.QScrollArea()
        side_scroll.setWidgetResizable(True)
        side_scroll.setFrameStyle(Qt.QFrame.NoFrame)
        side_inner = Qt.QWidget()
        self.controls_layout = Qt.QVBoxLayout(side_inner)
        self.controls_layout.setContentsMargins(0, 0, 0, 0)
        self.controls_layout.setSpacing(8)
        side_scroll.setWidget(side_inner)
        side_layout.addWidget(side_scroll, 1)

        self.status_label = Qt.QLabel("Ready")
        self.status_label.setObjectName("statusLabel")
        self.status_label.setWordWrap(True)
        side_layout.addWidget(self.status_label)
        splitter.addWidget(side_frame)

        plot_frame = Qt.QFrame()
        plot_frame.setObjectName("plotFrame")
        plot_layout = Qt.QVBoxLayout(plot_frame)
        plot_layout.setContentsMargins(8, 8, 8, 8)
        self.plot_host = plot_layout
        splitter.addWidget(plot_frame)
        splitter.setStretchFactor(0, 0)
        splitter.setStretchFactor(1, 1)
        splitter.setSizes([380, 900])

        self.settings = Qt.QSettings("GNU Radio", "bb60c_sweep_gui")
        try:
            self.restoreGeometry(self.settings.value("geometry"))
        except Exception:
            pass

        self.start_freq = 900e6
        self.stop_freq = 1000e6
        self.ref_level = -20.0
        self.sweep_time = 0.01
        self.rbw = 100e3
        self.vbw = 100e3
        self.rbw_shape = 1
        self.rejection = 0
        self.detector = 1
        self.scale = 0
        self.units = 0
        self.buffer_capacity = 32
        self.samp_rate = 32000

        self._apply_timer = Qt.QTimer(self)
        self._apply_timer.setSingleShot(True)
        self._apply_timer.setInterval(180)
        self._apply_timer.timeout.connect(self._flush_device_params)

        freq_box = self._make_group("Frequency")
        self._start_freq_range = Range(9e6, 6e9, 1e6, self.start_freq, 200)
        self._start_freq_win = RangeWidget(
            self._start_freq_range, self.set_start_freq,
            "Start", "counter_slider", float, QtCore.Qt.Horizontal)
        self._stop_freq_range = Range(9e6, 6e9, 1e6, self.stop_freq, 200)
        self._stop_freq_win = RangeWidget(
            self._stop_freq_range, self.set_stop_freq,
            "Stop", "counter_slider", float, QtCore.Qt.Horizontal)
        self._ref_level_range = Range(-50, 20, 1, self.ref_level, 200)
        self._ref_level_win = RangeWidget(
            self._ref_level_range, self.set_ref_level,
            "Ref Level (dBm)", "counter_slider", float, QtCore.Qt.Horizontal)
        freq_box.layout().addWidget(self._start_freq_win)
        freq_box.layout().addWidget(self._stop_freq_win)
        freq_box.layout().addWidget(self._ref_level_win)
        self.controls_layout.addWidget(freq_box)

        bw_box = self._make_group("Bandwidth")
        self._rbw_range = Range(1e3, 10e6, 1e3, self.rbw, 200)
        self._rbw_win = RangeWidget(
            self._rbw_range, self.set_rbw,
            "RBW", "counter_slider", float, QtCore.Qt.Horizontal)
        self._vbw_range = Range(1e3, 10e6, 1e3, self.vbw, 200)
        self._vbw_win = RangeWidget(
            self._vbw_range, self.set_vbw,
            "VBW", "counter_slider", float, QtCore.Qt.Horizontal)
        self._rbw_shape_tool_bar, self._rbw_shape_callback = self._make_chooser(
            "RBW Shape", [0, 1, 2], ["Nuttall", "Flattop", "CISPR"],
            self.rbw_shape, self.set_rbw_shape)
        bw_box.layout().addWidget(self._rbw_win)
        bw_box.layout().addWidget(self._vbw_win)
        bw_box.layout().addWidget(self._rbw_shape_tool_bar)
        self.controls_layout.addWidget(bw_box)

        acq_box = self._make_group("Acquisition")
        self._sweep_time_range = Range(0.001, 1, 0.001, self.sweep_time, 200)
        self._sweep_time_win = RangeWidget(
            self._sweep_time_range, self.set_sweep_time,
            "Sweep Time (s)", "counter_slider", float, QtCore.Qt.Horizontal)
        self._detector_tool_bar, self._detector_callback = self._make_chooser(
            "Detector", [0, 1], ["Min and Max", "Average"],
            self.detector, self.set_detector)
        self._rejection_tool_bar, self._rejection_callback = self._make_chooser(
            "Spur Reject", [0, 1], ["Off", "On"],
            self.rejection, self.set_rejection)
        self._scale_tool_bar, self._scale_callback = self._make_chooser(
            "Scale", [0, 1, 2, 3],
            ["Log", "Linear", "Log Full Scale", "Linear Full Scale"],
            self.scale, self.set_scale)
        self._units_tool_bar, self._units_callback = self._make_chooser(
            "Units", [0, 1, 2, 3],
            ["Log (dBm)", "Voltage", "Power", "Sample"],
            self.units, self.set_units)
        self._buffer_capacity_range = Range(1, 256, 1, self.buffer_capacity, 200)
        self._buffer_capacity_win = RangeWidget(
            self._buffer_capacity_range, self.set_buffer_capacity,
            "Buffer Capacity", "counter_slider", int, QtCore.Qt.Horizontal)
        for w in (self._sweep_time_win, self._detector_tool_bar,
                  self._rejection_tool_bar, self._scale_tool_bar,
                  self._units_tool_bar, self._buffer_capacity_win):
            acq_box.layout().addWidget(w)
        self.controls_layout.addWidget(acq_box)

        self.qtgui_time_sink_x_0 = qtgui.time_sink_f(
            1024, self.samp_rate, "", 1, None)
        self.qtgui_time_sink_x_0.set_update_time(0.10)
        self.qtgui_time_sink_x_0.set_y_axis(-1, 1)
        self.qtgui_time_sink_x_0.set_y_label('Amplitude', "")
        self.qtgui_time_sink_x_0.enable_tags(True)
        self.qtgui_time_sink_x_0.set_trigger_mode(
            qtgui.TRIG_MODE_TAG, qtgui.TRIG_SLOPE_POS, 0.0, 0, 0, "sweep_start")
        self.qtgui_time_sink_x_0.enable_autoscale(True)
        self.qtgui_time_sink_x_0.enable_grid(True)
        # Keep axis labels on so Y (Amplitude) remains; X "Time" title is
        # cleared after the widget is wrapped (see _clear_time_axis_title).
        self.qtgui_time_sink_x_0.enable_axis_labels(True)
        self.qtgui_time_sink_x_0.enable_control_panel(False)
        self.qtgui_time_sink_x_0.enable_stem_plot(False)
        self.qtgui_time_sink_x_0.disable_legend()

        self.trace_color = 'cyan'
        self.qtgui_time_sink_x_0.set_line_label(0, "Sweep")
        self.qtgui_time_sink_x_0.set_line_width(0, 1)
        self.qtgui_time_sink_x_0.set_line_color(0, self.trace_color)
        self.qtgui_time_sink_x_0.set_line_style(0, 1)
        self.qtgui_time_sink_x_0.set_line_marker(0, -1)
        self.qtgui_time_sink_x_0.set_line_alpha(0, 1.0)

        display_box = self._make_group("Display")
        self._trace_color_options = [
            'cyan', 'green', 'yellow', 'red', 'magenta', 'blue',
            'white', 'dark red', 'dark green', 'dark blue',
        ]
        self._trace_color_labels = [
            'Cyan', 'Green', 'Yellow', 'Red', 'Magenta', 'Blue',
            'White', 'Dark Red', 'Dark Green', 'Dark Blue',
        ]
        self._trace_color_swatch = Qt.QLabel()
        self._trace_color_swatch.setObjectName("colorSwatch")
        self._trace_color_swatch.setFixedHeight(18)
        self._trace_color_swatch.setMinimumWidth(80)
        self._update_color_swatch(self.trace_color)
        self._trace_color_tool_bar, self._trace_color_callback = self._make_chooser(
            "Trace Color",
            self._trace_color_options,
            self._trace_color_labels,
            self.trace_color,
            self.set_trace_color)
        display_box.layout().addWidget(self._trace_color_tool_bar)
        display_box.layout().addWidget(self._trace_color_swatch)
        self.controls_layout.addWidget(display_box)
        self.controls_layout.addStretch(1)

        self._qtgui_time_sink_x_0_win = sip.wrapinstance(
            self.qtgui_time_sink_x_0.qwidget(), Qt.QWidget)
        self.plot_host.addWidget(self._qtgui_time_sink_x_0_win)
        # Time Sink redraws "Time (ms)" when sample-rate/axis update; clear
        # repeatedly for a short window after startup and after reconfigs.
        self._time_label_clear_tries = 0
        self._time_label_timer = Qt.QTimer(self)
        self._time_label_timer.setInterval(200)
        self._time_label_timer.timeout.connect(self._clear_time_axis_title)
        self._time_label_timer.start()
        QtCore.QTimer.singleShot(0, self._clear_time_axis_title)

        self.bb60c_set_time_sink_nsamps_0 = blocks.msg_pair_to_var(
            getattr(self, 'qtgui_time_sink_x_0').set_nsamps)
        self.bb60c_bb60c_sweep_0 = bb60c.bb60c_sweep(
            self.ref_level, self.start_freq, self.stop_freq, self.rbw, self.vbw,
            self.sweep_time, self.rbw_shape, self.rejection, self.detector,
            self.scale, self.units, self.buffer_capacity)

        self.msg_connect(
            (self.bb60c_bb60c_sweep_0, 'num_points'),
            (self.bb60c_set_time_sink_nsamps_0, 'inpair'))
        self.connect((self.bb60c_bb60c_sweep_0, 0), (self.qtgui_time_sink_x_0, 0))
        self._update_status("Initialized")

    def _clear_time_axis_title(self):
        """
        @brief Removes the QT GUI Time Sink bottom-axis title "Time (ms)".

        Time Sink may rewrite the X-axis title when sample-rate units update.
        Clears QwtPlot xBottom title, QwtPlotAxisXBottom, and labels containing
        "Time".
        """
        win = getattr(self, "_qtgui_time_sink_x_0_win", None)
        if win is None:
            return

        cleared = False

        # 1) Blank QwtPlot xBottom title (QwtPlot::xBottom == 2).
        for child in win.findChildren(Qt.QWidget):
            if child.metaObject().className() != "TimeDomainDisplayPlot":
                continue
            try:
                ok = Qt.QMetaObject.invokeMethod(
                    child,
                    "setAxisTitle",
                    QtCore.Qt.DirectConnection,
                    Qt.Q_ARG("int", 2),
                    Qt.Q_ARG("QString", ""),
                )
                if ok:
                    cleared = True
            except Exception:
                pass

        # 2) Clear bottom scale widget title by objectName.
        for child in win.findChildren(Qt.QWidget):
            if child.objectName() != "QwtPlotAxisXBottom":
                continue
            try:
                if hasattr(child, "setTitle"):
                    child.setTitle("")
                    cleared = True
                ok = Qt.QMetaObject.invokeMethod(
                    child,
                    "setTitle",
                    QtCore.Qt.DirectConnection,
                    Qt.Q_ARG("QString", ""),
                )
                if ok:
                    cleared = True
            except Exception:
                pass

        # 3) Hide labels whose text contains "Time" (covers "Time (ms)").
        for child in win.findChildren(Qt.QWidget):
            cname = child.metaObject().className()
            if cname not in ("QwtTextLabel", "QLabel"):
                continue
            text = ""
            try:
                if hasattr(child, "text"):
                    text = str(child.text())
            except Exception:
                text = ""
            if "time" in text.lower():
                try:
                    if hasattr(child, "setText"):
                        child.setText("")
                    child.hide()
                    cleared = True
                except Exception:
                    pass

        self._time_label_clear_tries = getattr(self, "_time_label_clear_tries", 0) + 1
        if self._time_label_clear_tries >= 15 or (
            self._time_label_clear_tries >= 5 and cleared
        ):
            timer = getattr(self, "_time_label_timer", None)
            if timer is not None:
                timer.stop()

    def _apply_stylesheet(self):
        """Load the local QSS theme for the instrument window."""
        qss_path = os.path.join(
            os.path.dirname(os.path.abspath(__file__)), "bb60c_sweep.qss")
        try:
            with open(qss_path, "r", encoding="utf-8") as f:
                self.setStyleSheet(f.read())
        except OSError as exc:
            print("Warning: failed to load stylesheet:", exc)

    def _make_group(self, title):
        box = Qt.QGroupBox(title)
        layout = Qt.QVBoxLayout(box)
        layout.setContentsMargins(8, 16, 8, 8)
        layout.setSpacing(8)
        return box

    def _make_chooser(self, label, options, labels, current, setter):
        bar = Qt.QToolBar(self)
        bar.addWidget(Qt.QLabel(label + ":"))
        combo = Qt.QComboBox()
        for text in labels:
            combo.addItem(text)
        callback = lambda i, c=combo, o=options: Qt.QMetaObject.invokeMethod(
            c, "setCurrentIndex", Qt.Q_ARG("int", o.index(i)))
        callback(current)
        combo.currentIndexChanged.connect(lambda i, o=options: setter(o[i]))
        bar.addWidget(combo)
        setattr(self, "_{0}_combo_box".format(label.lower().replace(" ", "_")), combo)
        return bar, callback

    def _schedule_apply(self):
        self._apply_timer.start()

    def _flush_device_params(self):
        """Push the latest GUI values to the block after debounce."""
        if not hasattr(self, "bb60c_bb60c_sweep_0"):
            return
        start = min(self.start_freq, self.stop_freq)
        stop = max(self.start_freq, self.stop_freq)
        if stop <= start:
            stop = start + 1e6

        self.bb60c_bb60c_sweep_0.set_start_freq(start)
        self.bb60c_bb60c_sweep_0.set_stop_freq(stop)
        self.bb60c_bb60c_sweep_0.set_ref_level(self.ref_level)
        self.bb60c_bb60c_sweep_0.set_rbw(self.rbw)
        self.bb60c_bb60c_sweep_0.set_vbw(self.vbw)
        self.bb60c_bb60c_sweep_0.set_sweep_time(self.sweep_time)
        self.bb60c_bb60c_sweep_0.set_rbw_shape(self.rbw_shape)
        self.bb60c_bb60c_sweep_0.set_rejection(self.rejection)
        self.bb60c_bb60c_sweep_0.set_detector(self.detector)
        self.bb60c_bb60c_sweep_0.set_scale(self.scale)
        self.bb60c_bb60c_sweep_0.set_units(self.units)
        self._update_status("Applied")
        # Sink may rewrite axis units/title after parameter changes.
        self._time_label_clear_tries = 0
        if hasattr(self, "_time_label_timer") and not self._time_label_timer.isActive():
            self._time_label_timer.start()
        QtCore.QTimer.singleShot(0, self._clear_time_axis_title)

    def _update_status(self, prefix="Live"):
        span = abs(self.stop_freq - self.start_freq)
        text = (
            "{prefix}  |  {start} → {stop}  |  span {span}  |  "
            "RBW {rbw}  |  ref {ref:.1f} dBm"
        ).format(
            prefix=prefix,
            start=_fmt_hz(min(self.start_freq, self.stop_freq)),
            stop=_fmt_hz(max(self.start_freq, self.stop_freq)),
            span=_fmt_hz(span),
            rbw=_fmt_hz(self.rbw),
            ref=self.ref_level,
        )
        self.status_label.setText(text)

    def closeEvent(self, event):
        self.settings = Qt.QSettings("GNU Radio", "bb60c_sweep_gui")
        self.settings.setValue("geometry", self.saveGeometry())
        self.stop()
        self.wait()
        event.accept()

    def set_start_freq(self, start_freq):
        self.start_freq = float(start_freq)
        self._update_status("Pending")
        self._schedule_apply()

    def set_stop_freq(self, stop_freq):
        self.stop_freq = float(stop_freq)
        self._update_status("Pending")
        self._schedule_apply()

    def set_ref_level(self, ref_level):
        self.ref_level = float(ref_level)
        self._update_status("Pending")
        self._schedule_apply()

    def set_sweep_time(self, sweep_time):
        self.sweep_time = float(sweep_time)
        self._update_status("Pending")
        self._schedule_apply()

    def set_rbw(self, rbw):
        self.rbw = float(rbw)
        self._update_status("Pending")
        self._schedule_apply()

    def set_vbw(self, vbw):
        self.vbw = float(vbw)
        self._update_status("Pending")
        self._schedule_apply()

    def set_rbw_shape(self, rbw_shape):
        self.rbw_shape = int(rbw_shape)
        self._rbw_shape_callback(self.rbw_shape)
        self._update_status("Pending")
        self._schedule_apply()

    def set_rejection(self, rejection):
        self.rejection = int(rejection)
        self._rejection_callback(self.rejection)
        self._update_status("Pending")
        self._schedule_apply()

    def set_detector(self, detector):
        self.detector = int(detector)
        self._detector_callback(self.detector)
        self._update_status("Pending")
        self._schedule_apply()

    def set_scale(self, scale):
        self.scale = int(scale)
        self._scale_callback(self.scale)
        self._update_status("Pending")
        self._schedule_apply()

    def set_units(self, units):
        self.units = int(units)
        self._units_callback(self.units)
        self._update_status("Pending")
        self._schedule_apply()

    def _update_color_swatch(self, color_name):
        """Show a small preview chip for the selected trace color."""
        qt_colors = {
            'cyan': '#00ffff',
            'green': '#33cc66',
            'yellow': '#f0d84a',
            'red': '#ff4d4d',
            'magenta': '#e85ad8',
            'blue': '#4d8cff',
            'white': '#e8eef7',
            'dark red': '#a03030',
            'dark green': '#2f7a45',
            'dark blue': '#2a4f9e',
        }
        hex_color = qt_colors.get(color_name, '#00ffff')
        self._trace_color_swatch.setStyleSheet(
            "QLabel#colorSwatch {{"
            " background-color: {0};"
            " border: 1px solid #b78620;"
            " border-radius: 3px;"
            " }}".format(hex_color))

    def set_trace_color(self, trace_color):
        """
        @brief Updates the QT GUI Time Sink line color from the chooser.

        @param trace_color Named color accepted by qtgui.time_sink.set_line_color.
        """
        self.trace_color = str(trace_color)
        self._trace_color_callback(self.trace_color)
        self.qtgui_time_sink_x_0.set_line_color(0, self.trace_color)
        self._update_color_swatch(self.trace_color)
        self._update_status("Color {0}".format(self.trace_color))

    def set_buffer_capacity(self, buffer_capacity):
        self.buffer_capacity = int(buffer_capacity)
        self._update_status("Buffer is construction-only (restart to apply)")

    def get_samp_rate(self):
        return self.samp_rate

    def set_samp_rate(self, samp_rate):
        self.samp_rate = samp_rate
        self.qtgui_time_sink_x_0.set_samp_rate(self.samp_rate)


def main(top_block_cls=bb60c_sweep_gui, options=None):
    if StrictVersion("4.5.0") <= StrictVersion(Qt.qVersion()) < StrictVersion("5.0.0"):
        style = gr.prefs().get_string('qtgui', 'style', 'raster')
        Qt.QApplication.setGraphicsSystem(style)
    qapp = Qt.QApplication(sys.argv)

    tb = top_block_cls()
    tb.start()
    tb.show()

    def sig_handler(sig=None, frame=None):
        tb.stop()
        tb.wait()
        Qt.QApplication.quit()

    signal.signal(signal.SIGINT, sig_handler)
    signal.signal(signal.SIGTERM, sig_handler)

    timer = Qt.QTimer()
    timer.start(500)
    timer.timeout.connect(lambda: None)

    qapp.exec_()


if __name__ == '__main__':
    main()
